encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("Search", views.searchEntry, name="search"),
    path("CreateEntry", views.createEntry, name="create"),
    path("RandomEntryPage", views.randomEntry, name="random"),
    path("EditEntry/<str:entryname>", views.editEntry, name="edit"),
    path("<str:entryname>", views.entrypage, name="getentrypage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import random
import markdown2
from . import util

# open the home page with a list of entries
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

#  opens a specific entry
def entrypage(request, entryname):
    entry =util.get_entry(entryname)
    if entry:
        return render(request, "encyclopedia/entrypage.html", {
            "entry": markdown2.markdown(entry),
            "entryname": entryname
        })
    else:
        return render(request, "encyclopedia/entrypage.html", {
            "entry": entry,
            "entryname": entryname
        })

# get and render a random entry page
def randomEntry(request):
    # get a random entry name the all the list of entries
    entryname = random.choice(util.list_entries())
    return render(request, "encyclopedia/entrypage.html", {
        "entry": markdown2.markdown(util.get_entry(entryname)),
        "entryname": entryname
    })


# edit a specific entry
def editEntry(request, entryname):
    # // save edited entry page
    if request.method == "POST":
        content = request.POST['content']
        util.save_entry(entryname, content)
        return render(request, "encyclopedia/entrypage.html", {
            "entry": markdown2.markdown(util.get_entry(entryname)),
            "entryname": entryname
            })

    # open page for editing entry content
    return render(request, "encyclopedia/editEntry.html", {
        "entry": util.get_entry(entryname),
        "entryname": entryname
    })

# create an entry
def createEntry(request):
    if request.method =="POST":
        # get title and content of entry page
        title = request.POST['title']
        content = request.POST['content']
        entry = util.get_entry(title)
        # render page with error if title exist
        if entry:
            return render(request, "encyclopedia/createEntry.html", {
                "Error": "Title of entry page already exist",
                "content": content
            })
        else: 
            # save entry
            if title:
                util.save_entry(title, content)
                return render(request, "encyclopedia/createEntry.html")
            else:
                # render page with error if no title is entered
                return render(request, "encyclopedia/createEntry.html", {
                    "Error": "Title of entry page cannot be empty",
                    "content": content
                    })
    return render(request, "encyclopedia/createEntry.html")

def searchEntry(request):
    if request.method == "GET":
        # get the searched entry page name
        if request.GET['q']:
            entryname = request.GET['q']
            result = util.get_entry(entryname)
            # render page if entry name exist
            if result:
                 return render(request, "encyclopedia/entrypage.html", {
                    "entry": markdown2.markdown(result),
                    "entryname": entryname
                    })
            else:
                # search for entry page name that contains the search keyword
                entryList = util.list_entries()
                matchedEntries = []
                for entry in entryList:
                    if entryname.lower() in entry.lower():
                        matchedEntries.append(entry)
                # render the page with a list of entry page titles that contain the search
                # keyword
                return render(request, "encyclopedia/index.html", {
                    "entries": matchedEntries
                    })
        # render an error page if search box is empty
        else:
            return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "Error": "No search keyword provided"
            })
    # render home page if another method of request is used
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
            })

encyclopedia/templates/encyclopedia/createEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create Entry
{% endblock %}

{% block body %}

<h1>Create a New Page</h1>
<form action="{% url 'encyclopedia:create' %}" method="post">
    {% csrf_token %}
    <p>Title of Page</p>

    {% if Error %}
        <input type="text" name="title" id="title"> <span><b>{{Error}}</b></span>
        <p>Page Content</p>
        <textarea name="content" id="content" cols="20" rows="5">{{ content }}</textarea>

    {% else %}
        <input type="text" name="title" id="title">
        <p>Page Content</p>
        <textarea name="content" id="content" cols="20" rows="5"></textarea>
    {% endif %}

    <p><button type="submit">Save</button></p>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/editEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create Entry
{% endblock %}

{% block body %}

<h1>Edit "{{ entryname }}" Entry Page</h1>
<form action="/wiki/EditEntry/{{ entryname }}" method="post">
    {% csrf_token %}
    <p>Page Content</p>
    <textarea name="content" id="content" cols="20" rows="5">{{ entry }}</textarea>
    <p><button type="submit">Save</button></p>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/entrypage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ entryname }}
{% endblock %}

{% block body %}

{% if entry %}
    <p><a href="/wiki/EditEntry/{{ entryname }}">Edit</a></p>
    {{ entry | safe  }}

{% else %}
 <h1>Error Message</h1>
 <p>Requested page was no found</p>
{% endif%}

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

{% if Error %}
    <h1>{{Error}}</h1>
{% else %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}" > {{ entry }} </a></li>
        {% empty %}
            <li>No entry page found with the search keyword</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet"> 
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <div>
                        <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    </div>
                    <div>
                        <input class="search-btn" type="submit" value="Search">
                    </div>

                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>